### ISSUE TITLE
Add staging/production differentiations 

### ISSUE THREAD

**Issue by demery** [KislakCenter/VisualCollation#113]
- [ ] Add distinction between appearance of staging and production instances based on an environment variable

The environment variable could be something as simple as `VCEDITOR_STAGING_ENV`, which is active when set, and set only for the staging environment.

**Comment by lilblizzard** [comment]
1. Added route `/instance`
2. Added controller `instance_controller` which returns the `instance` environment variable
3. Return this variable to the front end in `NetworkErrorScreen`

**Comment by lilblizzard** [comment]
closed by #119
