### ISSUE TITLE
Add formula name to formula XSL output

### ISSUE THREAD

**Issue by demery** [KislakCenter/VisualCollation#44]
So that users can identify the type of each formula generated by `vceditor_idrovora/xproc/xpl/xsl/viscoll2formulas.xsl`, the output XML should contain the name of the formula type using an XML attribute or other means.

**Comment by acampagnolo** [comment]
I've added two attributes to the vc:formula element.
@type and @format
I don't have a specific name for the output formulas, so I guessed adding a format example would help. 
There will be formulas with a specific name, but a format is always useful I think.
I worked in the feature/20-formula-export branch, if this is not correct, let me know, and I'll update the correct branch.
